repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    name: Fixing common spelling mistakes
    args:
    - --write-changes
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.41.0
  hooks:
  - id: markdownlint
    name: Fixing markdown linting errors
    args: [--disable, MD013, --disable, MD024, --disable, MD029, --fix]
- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
  - id: absolufy-imports
    name: Make python imports absolute
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
    name: Python formatting (black)
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
  - id: docformatter
    name: Python docstring formatting (docformatter)
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    name: Sorting python imports
    args: [--profile, black]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.17.0
  hooks:
  - id: pyupgrade
    name: Upgrade common mistakes
    args: [--py38-plus]
- repo: https://github.com/PyCQA/flake8
  rev: 7.1.0
  hooks:
  - id: flake8
    name: Linting Python code (flake8)
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
    - flake8-simplify
    - pep8-naming
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.5
  hooks:
  - id: ruff
    name: Linting Python code (ruff)
    args: [--fix, --exit-non-zero-on-fix]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    args: [--autofix]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.0
  hooks:
  - id: mypy
    name: Static typechecking (mypy)
    exclude: ^tests/
# - repo: https://github.com/PyCQA/bandit
  # rev: 1.7.8
  # hooks:
  # - id: bandit
  #   name: Security linting (bandit)
