name: Ament Lint

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env: # We will have to keep it up-to-date with <https://docs.ros.org/en/foxy/Releases.html>
  ROS_DISTRO: humble
  UBUNTU_VERSION: 22.04

jobs:
  colcon-build:
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, flake8, mypy, pep257, pep8, xmllint] # A list of all available linters can be found at <https://index.ros.org/r/ament_lint/github-ament-ament_lint/>
    runs-on: ubuntu-${UBUNTU_VERSION}
    container:
      image: ubuntu:${UBUNTU_VERSION}
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: ${ROS_DISTRO}
    - uses: ros-tooling/action-ros-lint@master
      with:
        linter: ${{ matrix.linter }}
        package-name: ros2autodoc
